### ISSUE TITLE
pip install fails with --install-option="--prefix=/install"

### ISSUE THREAD

**Issue by perrymanuk** [TheLastProject/PyEssent#3]
I was trying to create a minimal docker image for home-assistant with includes PyEssent as a dependency, while I am not reliant on it and could just remove it it was failing with the install-option for prefixing the path.
Would be nice to have this fixed for anyone trying to create minimal images with your repo as a dependency :-D

**Comment by TheLastProject** [comment]
Do you have more info? Like the exact error message?

**Comment by TheLastProject** [comment]
Closed due to lack of response, feel free to reopen if you have the requested info.
