### ISSUE TITLE
Issue when having multiple connections

### ISSUE THREAD

**Issue by mdridder** [TheLastProject/PyEssent#5]
Hello,

When trying to integrate my essent stats with my home assistant i receive a warning that it couldnt find any meter readings. I do have turned on the option on the essent website. 

After some debugging I noticed that the problem might be related to multiple connections. I moved some years ago and both my old connection and new connection are available in the results. In the 'get_EANs' function it uses the first connection but in my case it needs to use the second one. (line 151)

An example of the connection part of my response:
`
<Connections>
    <Connection>
        <Address>old</Address>
        <Contracts>
            <Contract>
                <ConnectEAN>old_one</ConnectEAN>
            </Contract>
            <Contract>
                <ConnectEAN>old_ean</ConnectEAN>
            </Contract>
            <Contract>
                <ConnectEAN>old_ean</ConnectEAN>
            </Contract>
            <Contract>
                <ConnectEAN>old_ean</ConnectEAN>
            </Contract>
        </Contracts>
    </Connection>
    <Connection>
        <Address>new</Address>
        <Contracts>
            <Contract>
                <ConnectEAN>new_ean1</ConnectEAN>
            </Contract>
            <Contract>
                <ConnectEAN>new_ean2</ConnectEAN>
            </Contract>
        </Contracts>
    </Connection>
</Connections>
`

So probably the fix is that simple to just also loop over the connections.

Best,
Michel

**Comment by TheLastProject** [comment]
Should be fixed in #6.
