### ISSUE TITLE
Requirement is pinned for PyEssent 0.13: requests==2.22.0

### ISSUE THREAD

**Issue by MartinHjelmare** [TheLastProject/PyEssent#7]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by TheLastProject** [comment]
Interesting, I originally pinned it on this exact version because that was Home Assistant policy. Thanks for reaching out, so much happens with Home Assistant all the time it's easy to miss. I've created a commit for your request.

**Comment by MartinHjelmare** [comment]
Thank you!
